### ISSUE TITLE
Chrome extension has been desactivated !!!

### ISSUE THREAD

**Issue by CozmoCyke** [notlmn/copy-as-markdown#1]
Download the crx file and drop it into the the Chrome tab chrome://extensions.

Problem : Chrome has desactivated my extension immediately ! 

It's only possible to use Chrome extension available or puiblished on Chrome Store !

Could you publish this extension on Chrome Store ?

**Comment by notlmn** [comment]
Sorry, I wasn't aware that this issue existed. GitHub doesn't seem to automatically watch template repos and repos generated from templates.

-----------

> Problem : Chrome has desactivated my extension immediately !

You should unpack the crx file and load the unpacked directory in `chrome://extensions`.

Follow the steps from here: https://superuser.com/a/467379.

I know that this is not mentioned in the readme, but that's just how Chrome works these days.

--------------

> Could you publish this extension on Chrome Store ?

Google requires the user to pay a one time registration fee of 5 USD before you can start publishing extension, which me being a student and broke at the same time cannot afford to at the moment.

But I can assure you this will be in Chrome store once I can settle the finances. Top of my to-do list.

**Comment by yakov116** [comment]
@notlmn is there a donate link i can foot the bill

**Comment by notlmn** [comment]
![image](https://user-images.githubusercontent.com/37769974/62341198-003aed00-b500-11e9-8a60-66b4884c94a1.png)


Now there is! @yakov116 Thank you so much for considering donating to me. 🙇‍♂️

I was waiting for my @issuehunt bounties to be released to pay the bill myself and release this extension on CWS this month.

**Comment by yakov116** [comment]
@notlmn 	you deserve it!
Thanks for all you do at refined-github

**Comment by notlmn** [comment]
The extension is now published to Chrome Web Store at https://chrome.google.com/webstore/detail/copy-as-markdown/nlaionblcaejecbkcillglodmmfhjhfi.

Thanks to @yakov116 specially for this one ❤

Don't worry about the dated version, the extension should be automatically updated at the end of the day.
