### ISSUE TITLE
Copy issues when plain text

### ISSUE THREAD

**Issue by jasongaylord** [notlmn/copy-as-markdown#14]
When copying just plain text, it does not appear to copy anything. So, if there's nothing special to convert to Markdown, it won't copy.

**Comment by notlmn** [comment]
Hey @jasongaylord, can you provide a URL where you are facing this issue.

Copying plain text should not affect how the extension works, also can you provide the version of this extension you are using.

**Comment by jasongaylord** [comment]
It's in "new" Edge and is version 19.7.21.722 which I believe is the latest you have pushed to the Windows Store.

**Comment by jasongaylord** [comment]
And, it would be any single line or paragraph of text, such as my comment above.

**Comment by jasongaylord** [comment]
It works fine in Chrome using the current version of the plugin. It must be a difference between version 19 and 21.

**Comment by notlmn** [comment]
Edge is not something that we officially support, which we should. I was just testing publishing to "Edge Extension Store" to test stuff. And they don't yet have an API to automate that process, which as of right now requires manually uploading zip files on their dashboard.

I wasn't uploading any of the past few versions to the store as I actually forgot about that. Uploaded a new version to the store now, will update this issue when my submission passes their review process and gets published.

Thanks for using my extension 😃.

**Comment by jasongaylord** [comment]
Anytime. I posted about it here: https://jasong.us/3g279fv

**Comment by notlmn** [comment]
After 4 failed review submissions on the store, and 21 days later, the new version is finally submitted on the store. Thanks for the patience.

https://microsoftedge.microsoft.com/addons/detail/immegcobaplfimdjgkabakodipaehfca

**Comment by jasongaylord** [comment]
Cool. Thanks!

Sent from my phone
________________________________
