### ISSUE TITLE
[Feature] Support shortcut keys

### ISSUE THREAD

**Issue by Higurashi-kagome** [notlmn/copy-as-markdown#15]
Very useful tool! Thanks a lot.

But it might be more convenient if can support setting a shortcut（[chrome.commands](https://developer.chrome.com/docs/extensions/reference/commands/)） for triggering copy-as-markdown.

**Comment by notlmn** [comment]
I've haven't got the time recently to make many changes on the repo, but feel free to raise a pull-request if you can and I'd be happy to review.

**Comment by alanalvarado** [comment]
This feature is essential, I see someone did a pull request, but never got merged.
How can we make it happen?
Thanks in advance.

**Comment by Higurashi-kagome** [comment]
It's just because of my laziness😒... Updated the pull request just now, hope it is helpful. @alanalvarado
