### ISSUE TITLE
Support for mobile

### ISSUE THREAD

**Issue by theblack6688** [notlmn/copy-as-markdown#18]
右键复制，在移动端不能实现，希望能支持。
感谢开发者！

Right-click copy, which cannot be implemented on the mobile side. I hope it can be supported. 
Thanks to the developer!

浏览器举例：[kiwi ](https://kiwibrowser.com/)  、 http://static.lemurbrowser.com/assets/gitlab/Lemur_1_0_1_178.apk

Examples of browsers: [kiwi ](https://kiwibrowser.com/)  、 http://static.lemurbrowser.com/assets/gitlab/Lemur_1_0_1_178.apk

**Comment by notlmn** [comment]
I don't think any of the mobile browsers (even the one that you linked, which looks like a fork of Chromium) support adding items in context menus. The only major browser that supports extensions on mobile if Firefox, and they don't support this too.
