### ISSUE TITLE
Copy page link as markdown with title

### ISSUE THREAD

**Issue by fncll** [notlmn/copy-as-markdown#22]
I'm not sure if this is the place for a feature request, but it would be great if this extension provided a way to copy the current page as a markdown link using the page title for the link name.

**Comment by Higurashi-kagome** [comment]
It would be better to do this with [create-link](https://chrome.google.com/webstore/detail/create-link/gcmghdmnkfdbncmnmlkkglmnnhagajbm), and you will love it I think. @fncll

**Comment by fncll** [comment]
Perfect! Thanks for the pointer :)
