### ISSUE TITLE
Can't access options 

### ISSUE THREAD

**Issue by fducros** [notlmn/copy-as-markdown#23]
Can't access options
Hi all, I am using Copy as Markdown in Brave Browser. I cannot seem to get to the options menu as it doesn't display completely. Just the first line appears. How can I see and change the options (maybe directly in the files), to get a shortcut to copy as Markdown?

**Comment by notlmn** [comment]
There are no options for this extension.

Brave is an unsupported browser, you can try sharing a screenshot next time so that it's easier to see what's happening.
