### ISSUE TITLE
Keyboard Shortcut

### ISSUE THREAD

**Issue by vizog** [notlmn/copy-as-markdown#26]
The Chrome extension supports setting a shortcut to activate the extension but I can't find a way to set a keyboard shortcut for "copy link as markdown". 
Is it possible to add that ability to the extension?

**Comment by gsusI** [comment]
I can see that @Higurashi-kagome implemented this feature via #16. However, it isn't available when installing from the Chrome Web Store - it works fine when installed locally.

I've also noticed that the extension's page in the Web Store says that it was last updated in July 2020

![image](https://user-images.githubusercontent.com/4558016/210247583-7d8386d1-afa3-474f-b7f4-18ae15e79ad3.png)

@notlmn, could you confirm if the latest version of master was submitted and approved to the Chrome Web Store?

**Comment by notlmn** [comment]
These are some pending reviews on CWS, an automated release should fix this by tomorrow. Or I'll create a manual release.

**Comment by gsusI** [comment]
I can confirm that the latest version is now available on the CWS, and I'm enjoying the shortcuts.

Thank you both, @Higurashi-kagome and @notlmn! 🙌
