### ISSUE TITLE
link title is not right

### ISSUE THREAD

**Issue by srezasm** [notlmn/copy-as-markdown#31]
So far I haven't found any better copy as markdown extension, but still, it has the following issue.

By right click on the following link
`<a href="https://github.com/notlmn/copy-as-markdown">copy as markdown repository</a>`  
and selecting *copy link as markdown* option, it copies this:
`[https://github.com/notlmn/copy-as-markdown](https://github.com/notlmn/copy-as-markdown)`  
whereas it should copy this:  
`[copy as markdown repository](https://github.com/notlmn/copy-as-markdown)`

**Comment by notlmn** [comment]
This is a known issue with Chrome. See the following note from https://github.com/notlmn/copy-as-markdown#known-issues

> Note: When copying links and images, Chrome doesn’t let you extract images alt text or anchors text content to be used in Markdown, instead the links themselves are used as link title. Firefox doesn’t have this limitation though.
