### ISSUE TITLE
Hello! Online images cannot be copied and pasted into notes

### ISSUE THREAD

**Issue by zhouxinghong** [notlmn/copy-as-markdown#37]
Hello!
Online images cannot be copied and pasted into notes
Windows 10 19044
Chrome 120 | FireFox 120

If this problem can be solved, the extension will be very powerful and perfect.
Example image:
https://docs.github.com/assets/cb-82878/mw-1440/images/help/repository/headings-toc.webp

Thanks again for providing a very powerful browser extension! 👍😜

**Comment by notlmn** [comment]
The extension only deals with markdown, which is plain text.

Anything else is considered rich text, like in this case which involves making a request to some arbitrary URL and copying that to clipboard.

**Comment by zhouxinghong** [comment]
> That would be scope creep for what this extension is trying to do, one and only one thing, that is to handle markdown.
> 
> Having all sorts of features requested from different users added into this requires a lot of development efforts, increases complexity, and adds maintenance burden.

Makes sense, very good! 👍
