### ISSUE TITLE
Firefox extension needs to be manually activated before it works

### ISSUE THREAD

**Issue by tmewett** [notlmn/copy-as-markdown#39]
Context menu actions for this extension don't appear on pages by default. You have to click the extension in the menu to activate it:

![image](https://github.com/notlmn/copy-as-markdown/assets/3171736/3cece9a4-e0a1-4d81-86c5-10d705093799)

This doesn't happen with other extensions Tranquilize or LeechBlock - they are always shown.

If this can't be fixed, it would be great to make it so clicking the extension doesn't open the GitHub.

See #30 or https://github.com/yorkxin/copy-as-markdown/issues/109 for other discussion

**Comment by jasonmobley** [comment]
I still have this issue as well. Not sure why #30 was closed.
https://github.com/notlmn/copy-as-markdown/issues/30#issuecomment-1843510282

**Comment by Ambaquista** [comment]
Same problem!
Extension instaled, select a block and ... nothing in mouse-rightclick, nothing in the toolbar!

**Comment by notlmn** [comment]
This should be possible in the next release of the extension on Tuesday.
