### ISSUE TITLE
"Copy selection as markdown" does not work in Firefox.

### ISSUE THREAD

**Issue by poikilos** [notlmn/copy-as-markdown#4]
The "copy as markdown" feature is not working, though that would be the most useful feature for me ( "Copy image as markdown" and "Copy link as markdown" work). I am using

Browser: Firefox 73.0.1
OS: Fedora 31 or Windows

I tried it on:

1. a page with an advanced layout:
<https://start.fedoraproject.org/>
- Select an entire entry including the image
- Copy selection as markdown (fails)

2. a page with a simple layout:
<https://wiki.minetest.org/main/list_of_minetest_mobs.html>
- Go to the "Simple Mobs" section.
- Select an area starting before and ending after the image of the DM.
- Copy selection as markdown (fails)
- Select an area only containing text
- Copy selection as markdown (fails)

**Comment by notlmn** [comment]
Thanks for opening the issue @poikilos.

Have found and fixed the issue with this in https://github.com/notlmn/copy-as-markdown/commit/7b3500191403bef3eb035ff4dd9dc0a864442b2d. Expect a new release in the next day, and thanks again for giving the extension a try.

**Comment by notlmn** [comment]
@poikilos You should be able to install the new version of the extension from [here](https://addons.mozilla.org/en-US/firefox/addon/cpy-as-md/), or update if you have it already installed.

Let me know if you have any other issues related to the extension. Thanks!

**Comment by poikilos** [comment]
The cases above work now. Thanks!
