### ISSUE TITLE
Purpose of new permission to "Exchange messages with programs other than Firefox"?

### ISSUE THREAD

**Issue by ElhemEnohpi** [notlmn/copy-as-markdown#45]
I just got a message that I must grant this permission, aka nativeMessaging, for the new version. There's no explanation of why it's necessary. It seems to have replaced the clipboardWrite permission, but I can't find any information about why that might be.

**Comment by jaens** [comment]
Indeed, noticed the same thing. Changed here: https://github.com/notlmn/copy-as-markdown/commit/1e6eaf84d718e0e73e7097f795a1cd115c1d5fb9#diff-afd8f4f4844a5ad7b1b98d25703a5ce8238465fe439a9718083e279b925f44caR20

Perhaps an accident and should be reverted? I did not find anything about the MV3 migration requiring a change to the `clipboardWrite` permission.

**Comment by notlmn** [comment]
Fixing this in #47, the permission was never required in the first place.

**Comment by notlmn** [comment]
Surprisingly, Chrome release went through quick this time. With the latest release run, both Chrome and Firefox releases should have the fix now.

https://github.com/notlmn/copy-as-markdown/actions/runs/9733372736
