### ISSUE TITLE
24.6.30 no longer seems to work and there seems to be a permissions issue.

### ISSUE THREAD

**Issue by bwims** [notlmn/copy-as-markdown#50]
I am running Edge 126.0.2592.68 and this extension has worked well up until now.  Today it was disabled as mentioned in another issue, but after re-enabling, it no longer puts anything in the paste buffer although it appears to work.

Additionally, on the web store, it mention privilege requirements:

```
Permissions:

The extension requires the following permission from you for working.

1. `contextMenus`: to show option when right-clicking.
2. `activeTab`: to be able to access content on page.
```

However, these privileges are not enabled in Edge

![image](https://github.com/notlmn/copy-as-markdown/assets/18516073/62a73a83-7b26-4817-9333-5d7a3dedfaac)

Please advise, and thanks for an extension that is so useful that I have come to rely upon it!

B.

**Comment by notlmn** [comment]
This is similar to  #45.

The README doesn't reflect the published extension state, that lives in the tag that matches the version.

**Comment by bwims** [comment]
I'm afraid you didn't read the issue properly.

My **_main_** issue is that it is no longer transferring anything into the paste buffer. Please re-read,

`I am running Edge 126.0.2592.68 and this extension has worked well up until now. Today it was disabled as mentioned in another issue, but after re-enabling, it no longer puts anything in the paste buffer although it appears to work.`

**Comment by notlmn** [comment]
The version `24.6.30` is botched and there is a newer version `24.7.1` being released to Chrome Web Store and is pending review right now.

There would be no point trying to troubleshoot an older version that is known to have issues. Please wait until you get the newer release and see if that works for you.

**Comment by bwims** [comment]
Thanks!
