### ISSUE TITLE
It doesn't work anymore

### ISSUE THREAD

**Issue by hausen1012** [notlmn/copy-as-markdown#51]
And I cannot enable it
![image](https://github.com/notlmn/copy-as-markdown/assets/50026605/0a20634b-7b78-458a-8fba-860b47d93b27)
![image](https://github.com/notlmn/copy-as-markdown/assets/50026605/5e1a4ae0-9304-43c0-953c-8557b7705527)

**Comment by hausen1012** [comment]
My browser is Edge, version 126.0.2592.87

**Comment by bbt-dev** [comment]
The extension switches off eventually in Firefox, and when I enable it manually, it dies not work any more: there is a item in drop-down menu, but clicking on it does not copy neither markdown nor simple text in the clipboard. 
The extension indicates it was updated on July 1, 2024 - and this seems to be a culprit. Firefox version is 115.14.0esr (64)

**Comment by notlmn** [comment]
The warning on the UI at CWS doesn't exist anymore.

Edge is not officially supported.

**Comment by bbt-dev** [comment]
I am not sure why you indicated that the problem is "completed". I have the problem in Firefox version is 115.14.0esr (64) - i.e. latest. 
Do you suggest I open a new issue?
