### ISSUE TITLE
Convert relative links to absolute links

### ISSUE THREAD

**Issue by notlmn** [notlmn/copy-as-markdown#6]
From review: https://addons.mozilla.org/en-US/firefox/addon/cpy-as-md/reviews/1514624/

Relative links are rarely useful and the user has to convert them to absolute links anyway. (Except when copying as Markdown from GitHub rendered MD, but GH converts all relative links to absolute anyway).

Sample link: https://www.macports.org/install.php#help (last 2 paragraphs)

**Comment by seamusdemora** [comment]
Thanks for taking that on board & please let me know if I can do anything to help.

**Comment by notlmn** [comment]
I don't know when I'll be able to work on this, will try tonight.

The issue meanwhile is open for anyone to take and raise a PR and I'd be very happy to see that.

**Comment by CodingApps** [comment]
I'd like to assist with setting these to absolute links.

**Comment by notlmn** [comment]
Thanks for thinking of contributing to this @codingapps, you should be a able to set this repo locally, change the source code, and test if that works.

If you have any issues or questions, feel free to ping me (here or Twitter).

**Comment by notlmn** [comment]
@seamusdemora, this should be fixed now. Expect changes in extension in then next release.
