### ISSUE TITLE
There are unnecessary spaces when copying a list.

### ISSUE THREAD

**Issue by poikilos** [notlmn/copy-as-markdown#7]
## steps to reproduce issue
copy something like:
```
<ul>
<li>something</li>
<li>something</li>
<li>...</li>
</ul>
```

## actual behavior:
```
-   something
-   something
-   ...
```
## expected behavior
```
- something
- something
- ...
```

**Comment by notlmn** [comment]
Can you provide a link to where I can test this

**Comment by notlmn** [comment]
@poikilos, this should be fixed now. Expect changes in extension in then next release.
